version: '3'
services:
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - "../prometheus.yml:/etc/prometheus/prometheus.yml"
      - "../rules/:/etc/prometheus/rules/"
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'    
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - grafana_data:/var/lib/grafana

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - 3100:3100
    volumes:
      - ./loki-config.yaml:/mnt/config/loki-config.yaml
    command: --config.file=/mnt/config/loki-config.yaml
    
  
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./promtail-config.yaml:/mnt/config/promtail-config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log:ro
      - /var/log/nginx:/var/log/nginx:ro
    command: --config.file=/mnt/config/promtail-config.yaml -config.expand-env=true

  AlertManager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - 9093:9093
    restart: unless-stopped
    volumes:
      - "../alertmanager/email_alert.yml:/etc/alertmanager/email_alert.yml"
    command:
      - "--config.file=/etc/alertmanager/email_alert.yml"

volumes:
  prometheus-data:
  grafana_data: