version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - "../prometheus.yml:/etc/prometheus/prometheus.yml"
      - "../rules/:/etc/prometheus/rules/"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'    
    ports:
      - 9090:9090
      
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - 3100:3100
    volumes:
      - ../loki/loki-config.yaml:/mnt/config/loki-config.yaml
    command: --config.file=/mnt/config/loki-config.yaml
 
  alloy:
    image: grafana/alloy
    container_name: alloy
    ports:
      - 12345:12345
    volumes:
      - ./alloy-config.alloy:/etc/alloy/config.alloy
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy