
global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
      - targets:

rule_files:
  - './rules/prometheus.rules.yml'
  - './rules/alerting.rules.yml'

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
 

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
