
global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 'alertmanager:9093'

rule_files:
  - './rules/prometheus.rules.yml'
  - './rules/alerting.rules.yml'

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
 

  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Choose the module to use
    static_configs:
      - targets:
        - https://www.google.com
        - https://www.github.com
        - https://prometheus.io # Target to probe

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - target_label: instance
        replacement: blackbox
      - target_label: __address__
        replacement: blackbox:9115  # Blackbox Exporter address
  - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
    static_configs:
      - targets: ['blackbox:9115']
